In [3]:
arr = [1,2]

In [4]:
print(arr)

[1, 2]


In [5]:
arr?

Type:        list
String form: [1, 2]
Length:      2
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.


In [7]:
import numpy as np

In [8]:
np.array(arr)

array([1, 2])

In [9]:
arr.shape

AttributeError: 'list' object has no attribute 'shape'

In [10]:
arr_np = np.array(arr)

In [12]:
arr_np.shape

(2,)

In [17]:
shape = (1,2,3)
#rand_tensor = np.rand(shape)
ones_tensor = np.ones(shape)
zeros_tensor = np.zeros(shape)

#print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Ones Tensor: 
 [[[1. 1. 1.]
  [1. 1. 1.]]] 

Zeros Tensor: 
 [[[0. 0. 0.]
  [0. 0. 0.]]]
